class_name MatchLogic
extends RefCounted
## Pure matching. No node dependencies: everything comes in as Dictionaries
## (as loaded straight from data/*.json) and plain values.

## book: { "tags": Array[String], "rare": bool, ... }
## request: { "wants": Array[String], "avoid": Array[String], ... }
## customer: { "likes": Array[String], "dislikes": Array[String], ... }
## random_factor: the -1..+1 wobble from SPEC.md, generated by the caller
## (day.gd / returns.gd) so this function stays deterministic and testable.
static func score_match(book: Dictionary, request: Dictionary, customer: Dictionary, random_factor: int = 0) -> int:
	var tags: Array = book.get("tags", [])
	var wants: Array = request.get("wants", [])
	var avoid: Array = request.get("avoid", [])
	var likes: Array = customer.get("likes", [])
	var dislikes: Array = customer.get("dislikes", [])

	var score := 0
	for tag in tags:
		if wants.has(tag):
			score += Tuning.MATCH_WANTS_POINTS
		if likes.has(tag):
			score += Tuning.MATCH_LIKES_POINTS
		if avoid.has(tag):
			score += Tuning.MATCH_AVOID_POINTS
		if dislikes.has(tag):
			score += Tuning.MATCH_DISLIKES_POINTS

	return score + random_factor


## Tags are stored hyphenated so they compare cleanly; anywhere one is shown
## to the player it should read as words.
static func tag_label(tag: String) -> String:
	return tag.replace("-", " ")


## The tags that made this match good, for filling review-line templates.
static func matched_tags(book: Dictionary, request: Dictionary, customer: Dictionary) -> Array:
	var tags: Array = book.get("tags", [])
	var wants: Array = request.get("wants", [])
	var likes: Array = customer.get("likes", [])
	var result: Array = []
	for tag in tags:
		if wants.has(tag) or likes.has(tag):
			result.append(tag)
	return result


## The tags that made this match bad, for filling review-line templates.
static func clashing_tags(book: Dictionary, request: Dictionary, customer: Dictionary) -> Array:
	var tags: Array = book.get("tags", [])
	var avoid: Array = request.get("avoid", [])
	var dislikes: Array = customer.get("dislikes", [])
	var result: Array = []
	for tag in tags:
		if avoid.has(tag) or dislikes.has(tag):
			result.append(tag)
	return result
